-- Create database
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE Project1
COMMENT = 'Database for Project 1 FA';
USE DATABASE Project1;
-- Create schema
CREATE SCHEMA STAGE;
CREATE SCHEMA NDS;
CREATE SCHEMA DDS;

-- Create table
CREATE TABLE STAGE.Customer(
CustomerID INT PRIMARY KEY,
FirstName NVARCHAR(2048) NOT NULL,
LastName NVARCHAR(2048) NOT NULL,
Address NVARCHAR(2048) NOT NULL,
City NVARCHAR(2048) NOT NULL,
State NVARCHAR(2048) NOT NULL,
Territory NVARCHAR(2048) NOT NULL,
DateOfBirth DATETIME,
Gender NCHAR(64),
ModifiedDate DATETIME NOT NULL
);

CREATE TABLE STAGE.Product(
ProductID INT PRIMARY KEY,
ProductName NVARCHAR(2048) NOT NULL,
StandardCost FLOAT NOT NULL,
ListPrice FLOAT NOT NULL,
ProductCategory NVARCHAR(2048),
ModifiedDate DATETIME NOT NULL
);

CREATE TABLE STAGE.BillDetail(
BillDetailID INT PRIMARY KEY,
BillHeaderID INT NOT NULL,
OrderDate DATETIME NOT NULL,
CustomerID INT NOT NULL,
ProductID INT NOT NULL,
OrderQty INT NOT NULL,
UnitPrice FLOAT NOT NULL,
LineProfit FLOAT NOT NULL,
ModifiedDate DATETIME
);

CREATE TABLE NDS.Customer(
CustomerID INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(2048) NOT NULL,
LastName NVARCHAR(2048) NOT NULL,
DateOfBirth DATETIME,
Gender NCHAR(64),
ModifiedDate DATETIME NOT NULL
);

CREATE TABLE NDS.Territory(
TerritoryID INT IDENTITY(1,1) PRIMARY KEY,
Territory INT NOT NULL,
ModifiedDate DATETIME NOT NULL
);

CREATE TABLE NDS.State(
StateID INT IDENTITY(1,1) PRIMARY KEY,
State NVARCHAR(2048) NOT NULL,
TerritoryID INT NOT NULL,
ModifiedDate DATETIME NOT NULL,
FOREIGN KEY (TerritoryID) REFERENCES NDS.Territory(TerritoryID)
);

CREATE OR REPLACE TABLE NDS.Address(
AddressID INT IDENTITY(1,1) PRIMARY KEY,
CustomerID INT NOT NULL,
Address NVARCHAR(2048) NOT NULL,
City NVARCHAR(2048) NOT NULL,
StateID INT NOT NULL,
ModifiedDate DATETIME NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES NDS.Customer(CustomerID),
FOREIGN KEY (StateID) REFERENCES NDS.State(StateID)
);


CREATE TABLE NDS.ProductCategory(
ProductCategoryID INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(2048) NOT NULL,
ModifiedDate DATETIME NOT NULL
);

CREATE TABLE NDS.Product(
ProductID INT IDENTITY(1,1) PRIMARY KEY,
ProductName NVARCHAR(2048) NOT NULL,
ProductNumber NCHAR(64) NOT NULL,
StandardCost FLOAT NOT NULL,
ListPrice FLOAT NOT NULL,
ProductCategoryID INT NOT NULL,
ModifiedDate DATETIME NOT NULL,
FOREIGN KEY (ProductCategoryID) REFERENCES NDS.ProductCategory(ProductCategoryID)
);

CREATE TABLE NDS.BillHeader(
BillHeaderID INT IDENTITY(1,1) PRIMARY KEY,
CustomerID INT NOT NULL,
SubTotal FLOAT,
ModifiedDate DATETIME NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES NDS.Customer(CustomerID)
);

CREATE TABLE NDS.BillDetail(
BillDetailID INT IDENTITY(1,1) PRIMARY KEY,
BillHeaderID INT NOT NULL,
OrderQty INT NOT NULL,
ProductID INT NOT NULL,
UnitPrice FLOAT,
LineProfit FLOAT,
ModifiedDate DATETIME,
FOREIGN KEY (BillHeaderID) REFERENCES NDS.BillHeader(BillHeaderID),
FOREIGN KEY (ProductID) REFERENCES NDS.Product(ProductID)
);

USE SCHEMA DDS;
 
CREATE OR REPLACE TABLE DDS.DimCustomer
(CustomerKey INTEGER IDENTITY(1,1) PRIMARY KEY,
 SourceCustomerID INTEGER NOT NULL,
 Name VARCHAR(2048) NOT NULL,
 DateOfBirth DATE,
 Gender VARCHAR(64));
  
CREATE OR REPLACE TABLE DDS.DimLocation
(LocationKey INTEGER IDENTITY(1,1) PRIMARY KEY,
 SourceStateID INTEGER NOT NULL,
 State VARCHAR(2048) NOT NULL,
 Territory VARCHAR(2048) NOT NULL);
  
CREATE OR REPLACE TABLE DDS.DimProduct
(ProductKey INTEGER IDENTITY(1,1) PRIMARY KEY,
 SourceProductID INTEGER NOT NULL,
 ProductName VARCHAR(2048) NOT NULL,
 Category VARCHAR(2048) NOT NULL);
 
CREATE OR REPLACE TABLE DDS.DimCalendar
(Date DATE PRIMARY KEY, 
 Year SMALLINT NOT NULL,
 Month SMALLINT NOT NULL,
 Day SMALLINT NOT NULL,
 DayOfWeek VARCHAR(9) NOT NULL,
 Week SMALLINT NOT NULL)
AS
  WITH CTE_DATE AS (
    SELECT DATEADD(DAY, SEQ4(), '2000-01-01') AS Date
      FROM TABLE(GENERATOR(ROWCOUNT=>10000))  -- Number of days after reference date in previous line
  )
  SELECT Date, YEAR(Date), MONTH(Date), DAY(Date), DAYOFWEEK(Date), WEEKOFYEAR(Date) FROM CTE_DATE;

CREATE OR REPLACE TABLE DDS.FactSales
(BillDetailID INTEGER PRIMARY KEY,
 Date DATE NOT NULL,
 CustomerKey INTEGER NOT NULL,
 LocationKey INTEGER NOT NULL,
 ProductKey INTEGER NOT NULL,
 Volume INTEGER NOT NULL,
 Revenue FLOAT NOT NULL,
 Profit FLOAT NOT NULL,
FOREIGN KEY (ProductKey) REFERENCES DDS.DimProduct(ProductKey),
FOREIGN KEY (Date) REFERENCES DDS.DimCalendar(Date),
FOREIGN KEY (CustomerKey) REFERENCES DDS.DimCustomer(CustomerKey),
FOREIGN KEY (LocationKey) REFERENCES DDS.DimLocation(LocationKey));

-- Create file format
CREATE OR REPLACE FILE FORMAT PROJECT1.STAGE.CSV_FILE TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n'
SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
